
import Service.PlayFairCipher;
import Service.TimViTri;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nhan
 */
public class Sever extends javax.swing.JFrame {

    /**
     * Creates new form Sever
     */
    public Sever() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBanMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBanRo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtViTri = new javax.swing.JTextField();
        BtnGuiClient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTuKhoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GIAO THỨC UDP MÃ HOÁ VÀ GIẢI MÃ VĂN BẢN VỚI THUẬT TOÁN PLAYFAIR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bản mã:");

        txtBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanMaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Bản rõ:");

        txtBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanRoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Vị trí xuất hiện:");

        BtnGuiClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnGuiClient.setLabel("Gửi về Client");
        BtnGuiClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuiClientActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Khoá:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Từ Khoá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtBanMa, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(362, 362, 362)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(365, 365, 365)
                            .addComponent(BtnGuiClient))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanMa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnGuiClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanMaActionPerformed

    private void txtBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanRoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanRoActionPerformed

    private void BtnGuiClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuiClientActionPerformed
        try {
            while (true) {
                DatagramSocket datagramSocket = new DatagramSocket(5432);

                // đưa này vào trong while
                byte[] readBufferBanMa = new byte[1024];

                byte[] readBufferKhoa = new byte[1024];

                byte[] readBufferTuKhoa = new byte[1024];

                byte[] writeBuffer = new byte[1024];

                DatagramPacket receivePacketBanMa = new DatagramPacket(readBufferBanMa, readBufferBanMa.length);
                DatagramPacket receivePacketKhoa = new DatagramPacket(readBufferKhoa, readBufferKhoa.length);
                DatagramPacket receivePacketTuKhoa = new DatagramPacket(readBufferTuKhoa, readBufferTuKhoa.length);

                datagramSocket.receive(receivePacketBanMa);
                datagramSocket.receive(receivePacketKhoa);
                datagramSocket.receive(receivePacketTuKhoa);

                String lineBanMa = new String(receivePacketBanMa.getData()).trim();
                String lineKhoa = new String(receivePacketKhoa.getData()).trim();
                String lineTuKhoa = new String(receivePacketTuKhoa.getData()).trim();

                txtBanMa.setText(lineBanMa);
                txtKhoa.setText(lineKhoa);
                txtTuKhoa.setText(lineTuKhoa);

                System.out.println("Ban Ma: " + lineBanMa);
                System.out.println("Khoa: " + lineKhoa);
                System.out.println("Tu khoa: " + lineTuKhoa);
                /////Giải mã/////

                PlayFairCipher playFairCipher = new PlayFairCipher();
                String[][] table;

                String key = playFairCipher.parseString(txtKhoa.getText());
                System.out.println("khoa" + txtKhoa);
                if (key == "") {
                    JOptionPane.showMessageDialog(null, "please input key!");
                }

                ///
                table = playFairCipher.cipherTable(key);
                String outPut = txtBanMa.getText();
                String banRo = playFairCipher.decode(outPut);
                String lastStringAfterSplit = "";
                if (banRo.charAt(banRo.length() - 1) == 'X') {
                    lastStringAfterSplit = banRo.substring(0, banRo.length() - 1);

                } else {

                    lastStringAfterSplit = banRo;
                }

                txtBanRo.setText(lastStringAfterSplit);

                ///Tìm vị trí///
                TimViTri timViTri = new TimViTri();

                String tuKhoa = playFairCipher.parseString(txtTuKhoa.getText());

                String chuoiViTri = timViTri.TimViTri(banRo, tuKhoa);

                if (chuoiViTri == null || chuoiViTri =="") {
                    JOptionPane.showMessageDialog(null, "Empty Position!");
                } else {
                    txtViTri.setText(chuoiViTri);
                }

                // bỏ cái writeBuffer này
                //writeBuffer = line.getBytes();
                InetAddress host = receivePacketBanMa.getAddress();
                int port = receivePacketBanMa.getPort();

                writeBuffer = txtViTri.getText().getBytes();

                DatagramPacket sendPacket = new DatagramPacket(writeBuffer, writeBuffer.length, host, port);
                datagramSocket.send(sendPacket);

//               
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_BtnGuiClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sever().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuiClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBanMa;
    private javax.swing.JTextField txtBanRo;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtTuKhoa;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
